version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    expose:
      - 5000
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
